# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class Test1():
    def setup_method(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_1(self):
        self.driver.get("https://www.office.com/")
        self.driver.set_window_size(1295, 695)
        self.driver.find_element(
            By.ID, "hero-banner-sign-in-to-office-365-link").click()

        self.driver.find_element(By.ID, "i0116").send_keys(
            "EMAIL HERE")
        self.driver.find_element(By.ID, "idSIButton9").click()
        element = WebDriverWait(self.driver, 10)
        self.driver.find_element(By.ID, "i0118").send_keys("PASSWORD HERE")
        element.until(
            EC.invisibility_of_element_located((By.XPATH,
                                                "//div[@class='lightbox-cover']"))
        )

        self.driver.implicitly_wait(5)

        self.driver.find_element(By.ID, "idSIButton9").click()
        element = self.driver.find_element(
            By.ID, "activity-description-div-012BLMK7THXEICLAMYHFB36ZDPXIEJIC4A")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()


x = Test1()
x.setup_method()
x.test_1()
